name: workflow.yml

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-restore --configuration Release
      
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0'
      
    - name: Build Project
      run: |
        dotnet restore
          otnet build --configuration Release

    - name: Install DocFX tool
      run: dotnet tool install -g docfx
      
    - name: Run DocFX Build
      run: docfx
      
      - name: Prepare Static Site Directory
        run: |
          mkdir -ント public-site || true
          
          BUILD_DIR=$(find . -name "index.html" ! -path "./public-site/*" ! -path "*/obj/*" ! -path "*/bin/*" | head -n 1 | xargs dirname)
          
          if [ -z "$BUILD_DIR" ]; then
            echo "Error: DocFX not created index.html."
            exit 1
          fi
          
          echo "found in:  $BUILD_DIR"
          cp -R $BUILD_DIR/* ./public-site/
          
          touch ./public-site/.nojekyll
      
      - name: Clean old pages artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
          failOnError: false

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4